twitter:
  consumer_key: Ma7ngXmdzNtvkT6vMlV12w
  consumer_secret: m4JaE4NoxDty1spvgMWEe1DxilSTb9EA51G9TBgy08

facebook:
  consumer_key: 403035429759454
  consumer_secret: b43d7a9a28e8920c5cdfce21dc96154b
